export type DataType = {
    valid: boolean
    timestapm: number
    base: string
    rates: RatesType
}

export type RatesType = {
    AED?: number
    AFN?: number
    ALL?: number
    AMD?: number
    ANG?: number
    AOA?: number
    ARS?: number
    AUD?: number
    AWG?: number
    AZN?: number
    BAM?: number
    BBD?: number
    BCH?: number
    BDT?: number
    BGN?: number
    BHD?: number
    BIF?: number
    BMD?: number
    BND?: number
    BOB?: number
    BRL?: number
    BSD?: number
    BTC?: number
    BTG?: number
    BWP?: number
    BZD?: number
    CAD?: number
    CDF?: number
    CHF?: number
    CLP?: number
    CNH?: number
    CNY?: number
    COP?: number
    CRC?: number
    CUC?: number
    CUP?: number
    CVE?: number
    CZK?: number
    DAS?: number
    DJF?: number
    DKK?: number
    DOP?: number
    DZD?: number
    EGP?: number
    EOS?: number
    ETB?: number
    ETH?: number
    EUR?: number
    FJD?: number
    GBP?: number
    GEL?: number
    GHS?: number
    GIP?: number
    GMD?: number
    GNF?: number
    GTQ?: number
    GYD?: number
    HKD?: number
    HNL?: number
    HRK?: number
    HTG?: number
    HUF?: number
    IDR?: number
    ILS?: number
    INR?: number
    IQD?: number
    IRR?: number
    ISK?: number
    JMD?: number
    JOD?: number
    JPY?: number
    KES?: number
    KGS?: number
    KHR?: number
    KMF?: number
    KRW?: number
    KWD?: number
    KYD?: number
    KZT?: number
    LAK?: number
    LBP?: number
    LKR?: number
    LRD?: number
    LSL?: number
    LTC?: number
    LYD?: number
    MAD?: number
    MDL?: number
    MKD?: number
    MMK?: number
    MOP?: number
    MUR?: number
    MVR?: number
    MWK?: number
    MXN?: number
    MYR?: number
    MZN?: number
    NAD?: number
    NGN?: number
    NIO?: number
    NOK?: number
    NPR?: number
    NZD?: number
    OMR?: number
    PAB?: number
    PEN?: number
    PGK?: number
    PHP?: number
    PKR?: number
    PLN?: number
    PYG?: number
    QAR?: number
    RON?: number
    RSD?: number
    RUB?: number
    RWF?: number
    SAR?: number
    SBD?: number
    SCR?: number
    SDG?: number
    SEK?: number
    SGD?: number
    SLL?: number
    SOS?: number
    SRD?: number
    SVC?: number
    SZL?: number
    THB?: number
    TJS?: number
    TMT?: number
    TND?: number
    TOP?: number
    TRY?: number
    TTD?: number
    TWD?: number
    TZS?: number
    UAH?: number
    UGX?: number
    USD?: number
    UYU?: number
    UZS?: number
    VND?: number
    XAF?: number
    XAG?: number
    XAU?: number
    XCD?: number
    XLM?: number
    XOF?: number
    XRP?: number
    YER?: number
    ZAR?: number
    ZMW?: number
}